(()=>{
  if(new URLSearchParams(location.search).get('bossTest')!=='1'||window.__obdGymXpTest)return;
  window.__obdGymXpTest=true;
  const XP_KEY='obd_gym_test_xp_v2',GYM_KEY='obd_gym_test_v5',MAX_TEST_XP=92;
  const RANKS_FALLBACK=['Couch Recruit','Rep Collector','Hemorrhoid Pumper','Protein Junkie','Pump Chaser','Iron Disciple','Disciplined Lifter','Big Dawg','Meat Machine','Gym Warlord'];
  let lastPlayer='';
  const playerId=()=>window.getSelectedPlayerId?.()||'test-player',playerName=()=>window.getSelectedPlayer?.()||'TEST PLAYER';
  const read=()=>{try{return JSON.parse(localStorage.getItem(XP_KEY)||'null')||{players:{}}}catch{return{players:{}}}},write=v=>{try{localStorage.setItem(XP_KEY,JSON.stringify(v))}catch{}return v};
  const levelFromXp=xp=>Math.min(10,Math.floor(Math.max(0,Number(xp)||0)/10)+1),rankFor=l=>{try{return typeof RANKS!=='undefined'&&RANKS[l-1]?RANKS[l-1]:RANKS_FALLBACK[l-1]}catch{return RANKS_FALLBACK[l-1]}};
  const today=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`},addDays=(s,n)=>{const [y,m,d]=s.split('-').map(Number),x=new Date(Date.UTC(y,m-1,d+n));return x.toISOString().slice(0,10)};
  function state(){const map=read(),id=playerId();map.players=map.players||{};map.players[id]=map.players[id]||{xp:0,workouts:0,startDate:today(),lastDate:''};write(map);return map.players[id]}
  function save(next){const map=read(),id=playerId();map.players=map.players||{};map.players[id]=next;write(map);return next}
  function testLevel(){return levelFromXp(state().xp)}window.getGymTestXp=()=>Number(state().xp)||0;window.getGymTestLevel=testLevel;
  function style(){if(document.getElementById('gymTestXpStyle'))return;const s=document.createElement('style');s.id='gymTestXpStyle';s.textContent=`.gym-test-xp{margin:10px 0 8px;padding:10px 11px;border:1px dashed rgba(250,204,21,.4);border-radius:15px;background:linear-gradient(145deg,rgba(37,29,6,.94),rgba(12,16,22,.96))}.gym-test-xp-head,.gym-test-xp-row,.gym-test-xp-meta{display:flex;align-items:center;justify-content:space-between;gap:8px}.gym-test-xp-head span{font-size:8px;font-weight:1000;letter-spacing:.14em;color:#facc15}.gym-test-xp-head b{font-size:7px;color:#8b96a3}.gym-test-xp-row{margin-top:8px}.gym-test-xp-stat{min-width:52px}.gym-test-xp-stat small{display:block;font-size:6px;color:#7d8b98;font-weight:900}.gym-test-xp-stat strong{display:block;margin-top:1px;font-size:14px;color:#fff}.gym-test-xp-add,.gym-test-xp-reset{border:1px solid rgba(255,255,255,.1);border-radius:10px;padding:8px 10px;font-size:8px;font-weight:1000;cursor:pointer}.gym-test-xp-add{background:linear-gradient(135deg,#eab308,#f97316);color:#150f02}.gym-test-xp-add:disabled{filter:grayscale(1);opacity:.45}.gym-test-xp-reset{background:#101821;color:#81909d}.gym-test-xp-track{height:6px;margin-top:8px;border-radius:99px;background:#1a2027;overflow:hidden}.gym-test-xp-track i{display:block;height:100%;background:linear-gradient(90deg,#eab308,#fb923c);border-radius:inherit;transition:.25s}.gym-test-xp-meta{margin-top:6px;font-size:7px;color:#81909d}.gym-test-xp-meta b{color:#e5e7eb}.gym-test-xp-note{margin-top:6px;padding-top:6px;border-top:1px solid rgba(255,255,255,.05);font-size:7px;line-height:1.45;color:#a7b0b8}.gym-test-xp-note strong{color:#facc15}@media(max-width:390px){.gym-test-xp-row{flex-wrap:wrap}.gym-test-xp-add{flex:1}}`;document.head.appendChild(s)}
  function controls(){style();let e=document.getElementById('gymTestXpControls');if(!e){e=document.createElement('section');e.id='gymTestXpControls';e.className='gym-test-xp';const r=document.getElementById('rewardEngine');r?.parentNode?r.insertAdjacentElement('afterend',e):document.querySelector('.app-shell')?.prepend(e)}return e}
  function render(){const p=state(),xp=Number(p.xp)||0,l=levelFromXp(xp),base=(l-1)*10,next=l>=10?xp:l*10,pct=l>=10?100:(xp-base)/10*100,e=controls(),note=l<3?'<strong>GYM LOCKED</strong> · Workout until Level 3.':l<8?'<strong>GYM ACTIVE</strong> · #149–151 remain locked until Level 8.':l<10?'<strong>#149–151 UNLOCKED</strong> · They can appear from the next generated encounter.':'<strong>LEVEL 10</strong> · Keep fighting until GymDex is complete.';e.innerHTML=`<div class="gym-test-xp-head"><span>TEST: SIMULATED TRAINING</span><b>LOCAL ONLY</b></div><div class="gym-test-xp-row"><div class="gym-test-xp-stat"><small>LEVEL</small><strong>${l}/10</strong></div><div class="gym-test-xp-stat"><small>XP</small><strong>${xp}</strong></div><div class="gym-test-xp-stat"><small>STRENGTH</small><strong>${p.workouts}</strong></div><div class="gym-test-xp-stat"><small>RANK</small><strong style="font-size:8px">${rankFor(l)}</strong></div><button class="gym-test-xp-add" data-add ${xp>=MAX_TEST_XP?'disabled':''}>+4 XP · +1 STYRKE</button><button class="gym-test-xp-reset" data-reset>RESET</button></div><div class="gym-test-xp-track"><i style="width:${pct}%"></i></div><div class="gym-test-xp-meta"><span>${l>=10?'MAX LEVEL':`${next-xp} XP TO LEVEL ${l+1}`}</span><b>${p.lastDate?`LAST SIM DAY ${p.lastDate}`:'NO SIMULATED WORKOUTS YET'}</b></div><div class="gym-test-xp-note">Each click = <strong>one strength workout on a new day</strong> and earns one Gym attack after Level 3. ${note}</div>`;e.querySelector('[data-add]')?.addEventListener('click',addWorkout);e.querySelector('[data-reset]')?.addEventListener('click',reset)}
  function addWorkout(){const old=state(),beforeXp=Number(old.xp)||0,before=levelFromXp(beforeXp),workouts=Number(old.workouts||0)+1,date=addDays(old.startDate||today(),workouts-1),afterXp=Math.min(MAX_TEST_XP,beforeXp+4),after=levelFromXp(afterXp),next=save({...old,xp:afterXp,workouts,lastDate:date});render();if(after>before&&typeof toast==='function')toast(`TEST LEVEL ${after} · ${rankFor(after)}`);window.dispatchEvent(new CustomEvent('obd-gym-test-workout',{detail:{person:playerName(),playerId:playerId(),type:'strength',xpDelta:4,levelBefore:before,levelAfter:after,newTrainingDay:true,test:true,simulatedDate:date,simulatedWorkoutNumber:next.workouts}}));window.refreshGymLeader?.()}
  function reset(){if(!confirm('Reset LOCAL test XP, simulated workouts, Gym story and stolen Pokémon? Real data is untouched.'))return;try{localStorage.removeItem(XP_KEY);localStorage.removeItem(GYM_KEY)}catch{}render();window.refreshGymLeader?.();if(typeof toast==='function')toast('Local full-game test reset')}
  function boot(){const id=playerId();if(id!==lastPlayer){lastPlayer=id;render()}else controls();if(typeof window.refreshGymLeader==='function')window.refreshGymLeader();else setTimeout(boot,100)}
  render();boot();window.addEventListener('obd-player-changed',()=>{lastPlayer='';render();window.refreshGymLeader?.()});
})();