import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=Deno.env.get('SUPABASE_URL')!;const K=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const PIN=Deno.env.get('APP_PIN')||'1337';
const C={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type, authorization, apikey','Access-Control-Allow-Methods':'GET, POST, OPTIONS'};const J={...C,'content-type':'application/json'};const H={'apikey':K,'Authorization':`Bearer ${K}`,'Content-Type':'application/json'};const out=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:J});
const keys=['power','engine','discipline','grit'];
function norm(v:any){const o:any={power:0,engine:0,discipline:0,grit:0};for(const k of keys){const n=Number(v?.[k]||0);if(!Number.isInteger(n)||n<0)throw new Error('INVALID');o[k]=n}return o}
const spent=(a:any)=>keys.reduce((s,k)=>s+a[k],0);const released=(a:any,b:any)=>keys.reduce((s,k)=>s+Math.max(0,a[k]-b[k]),0);
async function base(body:any){const r=await fetch(`${U}/functions/v1/player-stats`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,pin:PIN})});const t=await r.text();let d:any={};try{d=t?JSON.parse(t):{}}catch{};return{ok:r.ok,status:r.status,data:d}}
function enrich(d:any){const a=norm(d.stats_alloc),cap=Number(d.total_ap)||0,u=Math.max(0,cap-spent(a));return{...d,stats_alloc:a,spent_ap:spent(a),unspent_ap:u,can_allocate:u>0,respec_open:!!d.build_open,respec_limit:10}}
async function patch(id:string,body:any){const r=await fetch(`${U}/rest/v1/players?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{...H,Prefer:'return=representation'},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text())}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:C});if(req.method==='GET')return out({ok:true,service:'player-stats-flex-v1'});try{const b=await req.json();if(String(b.pin||'')!==PIN)return out({error:'Feil PIN'},403);const id=String(b.player_id||'');if(!id)return out({error:'player_id required'},400);if(b.action==='get'||b.action==='unlock'){const r=await base({action:b.action,player_id:id});return out(enrich(r.data),r.status)}if(b.action==='set'){const g=await base({action:'get',player_id:id});if(!g.ok)return out(g.data,g.status);const before=norm(g.data.stats_alloc);let after:any;try{after=norm(b.stats_alloc)}catch{return out({error:'Ugyldig stat-fordeling'},400)}const cap=Number(g.data.total_ap)||0;if(spent(after)>cap)return out({error:`Du har kun ${cap} AP på Level ${g.data.current_level}`},400);const moved=released(before,after);if(moved>0&&!g.data.build_open)return out({...enrich(g.data),error:'Tildelte AP er låst. AP kan bare frigjøres ved level up.'},409);if(moved>10)return out({...enrich(g.data),error:'Du kan maksimalt frigjøre 10 AP per level up.'},400);const p:any={stats_alloc:after};if(g.data.build_open){p.stats_build_saved_level=g.data.current_level;p.stats_build_open_level=null}await patch(id,p);const fresh=await base({action:'get',player_id:id});return out({...enrich(fresh.data),respec_released:moved,respec_consumed:!!g.data.build_open},fresh.status)}return out({error:'Bad request'},400)}catch(e){console.error(e);return out({error:'Server error'},500)}});
